$(window).resize(function(){if(this.resizeTO)clearTimeout(this.resizeTO);this.resizeTO=setTimeout(function(){$(this).trigger('resizeEnd');},500);});function pais(pais,iso){var data;google.charts.load('current',{'packages':['geochart'],'mapsApiKey':'AIzaSyD-9tSrke72PouQMnMX-a7eZSW0jkFMBWY'});google.charts.setOnLoadCallback(drawChart);function drawChart(){var reg,col;reg=pais?iso:'world';col=pais?'#F5F5F5':'#F0F8FF';data=google.visualization.arrayToDataTable([['Country'],[pais]]);var options={region:reg,resolution:'region',defaultColor:'#22a7c0',datalessRegionColor:col};var chart=new google.visualization.GeoChart(document.getElementById('regions_div'));chart.draw(data,options);}
$(window).on('resizeEnd',function(){drawChart(data);});}
function nav(){var data;google.charts.load("current",{packages:["corechart"]});google.charts.setOnLoadCallback(drawChart);function drawChart(){data=google.visualization.arrayToDataTable([['Browser','Share'],['Chrome',54.27],['Safari',14.17],['UC',8.59],['Firefox',5.72],['Opera',3.99],['IE',3.73],['Samsung',3.53],['Other',6]]);var options={title:'Global Share',pieHole:0.4,slices:{1:{color:'#81c3f6'},2:{color:'#ffd900'},0:{color:'#22a7c0'}}};var chart=new google.visualization.PieChart(document.getElementById('donutchart'));chart.draw(data,options);}
$(window).on('resizeEnd',function(){drawChart(data);});}
function os(){var data;google.charts.load("current",{packages:['corechart']});google.charts.setOnLoadCallback(drawChart);function drawChart(){data=google.visualization.arrayToDataTable([["OS","Percentage",{role:"style"}],["Android",40.72,'#dcdcdc'],["Windows",35.16,'#dcdcdc'],["iOS",13.22,'#dcdcdc'],["OSX",4.64,'#dcdcdc'],["Unknown",2.99,'#dcdcdc'],["Linux",0.77,'#dcdcdc'],['Other',2.5,'#dcdcdc']]);var view=new google.visualization.DataView(data);view.setColumns([0,1,{calc:"stringify",sourceColumn:1,type:"string",role:"annotation"},2]);var options={title:"Share",bar:{groupWidth:"90%"},legend:{position:"none"}};var chart=new google.visualization.ColumnChart(document.getElementById("top_x_div"));chart.draw(view,options);}
$(window).on('resizeEnd',function(){drawChart(data);});}
function dev(){var data;google.charts.load('current',{'packages':['corechart']});google.charts.setOnLoadCallback(drawChart);function drawChart(){data=google.visualization.arrayToDataTable([['Device','Percentage'],['Mobile',54.08],['Desktop',41.12],['Tablet',4.8]]);var options={title:'Global Share',slices:{1:{color:'#81c3f6'},2:{color:'#ffd900'},0:{color:'#22a7c0'}}};var chart=new google.visualization.PieChart(document.getElementById('piechart'));chart.draw(data,options);}
$(window).on('resizeEnd',function(){drawChart(data);});}
function copy(){var div,ip,isiOSDevice;div=document.getElementById('copiar');ip=document.getElementById('ip');isiOSDevice=navigator.userAgent.match(/ipad|iphone/i);div.onclick=function(){var textArea=document.createElement("textarea");textArea.style.position='fixed';textArea.style.top=0;textArea.style.left=0;textArea.style.width='2em';textArea.style.height='2em';textArea.style.padding=0;textArea.style.border='none';textArea.style.outline='none';textArea.style.boxShadow='none';textArea.style.background='transparent';textArea.value=ip.innerHTML;document.body.appendChild(textArea);if(isiOSDevice){var editable=textArea.contentEditable;var readOnly=textArea.readOnly;textArea.contentEditable=true;textArea.readOnly=true;var range=document.createRange();range.selectNodeContents(textArea);var selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);textArea.setSelectionRange(0,999999);textArea.contentEditable=editable;textArea.readOnly=readOnly;}else{textArea.select();}
try{var successful=document.execCommand('copy');var msg=successful?'successful':'unsuccessful';console.log('Copying text command was '+msg);}catch(err){console.log('Oops, unable to copy');}
document.body.removeChild(textArea);div.innerHTML='copied!';};}
function ref(){return document.referrer?document.referrer.match(/:\/\/(.[^/]+)/)[1]:'None';}